package com.ds.goroute.type;

public enum NotificationType {
    TRIP_INVITE, MEMBER_JOINED, MEMBER_LEFT, ACTIVITY_ADDED, ACTIVITY_UPDATED, 
    ACTIVITY_DELETED, CHECKIN, EXPENSE_ADDED, ROUTE_OPTIMIZED, TRIP_REMINDER
}
