#!/usr/bin/env node
/**
 * Builds the SQL that loads the Vietnamese administrative boundaries (34 provinces,
 * 3 321 wards) from thanglequoc/vietnamese-provinces-database into the goroute schema
 * created by V170__geo_boundaries.sql.
 *
 * Why a script and not a Flyway migration: the GeoJSON archive is ~630 MB unpacked.
 * The SQL this emits is still large (~100 MB); it is meant for `psql -f`, not for the
 * application's startup path. Run it once per dataset release, then trigger the admin
 * backfill (POST /v1/api/admin/geo/backfill) so the code-level remap 63 -> 34 and the
 * ward assignment of places/check-ins happen.
 *
 * Usage:
 *   unzip -q vn_provinces_wards_geojson.zip -d <work>
 *   node build_geo_sql.mjs \
 *     --units <work>/full_json_generated_data_vn_units.json \
 *     --metadata <work>/vn_provinces_metadata.json \
 *     --geojson-dir <work>/geojson \
 *     --remap ./remap_63_to_34.json \
 *     --out ../../data/geo/geo_dataset_v5.1.0.sql
 *
 * Requires `npx mapshaper` (downloaded on first use). Two geometries per unit are kept:
 * `geom` at full resolution (point-in-polygon) and `geom_display` simplified (drawn on
 * the phone). keep-shapes stops small islands vanishing at the display level.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const args = parseArgs(process.argv.slice(2));
const unitsPath = required('units');
const metadataPath = required('metadata');
const geojsonDir = required('geojson-dir');
const remapPath = required('remap');
const outPath = required('out');
// --mapshaper points at the CLI script (node_modules/mapshaper/bin/mapshaper); it is a
// shebang file, so on Windows it has to be run through node rather than executed.
const mapshaperBin = args.mapshaper ? path.resolve(args.mapshaper) : null;
const mapshaperCmd = mapshaperBin ? process.execPath : 'npx';
const mapshaperPrefix = mapshaperBin ? [mapshaperBin] : ['--yes', 'mapshaper'];
const WARD_DISPLAY_INTERVAL = args['ward-interval'] || '30m';
const PROVINCE_DISPLAY_INTERVAL = args['province-interval'] || '200m';

const units = JSON.parse(fs.readFileSync(unitsPath, 'utf8'));
const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
const remap = JSON.parse(fs.readFileSync(remapPath, 'utf8'));
const datasetVersion = metadata.DatasetVersion;
if (!datasetVersion) fail('metadata has no DatasetVersion');

const provincesByCode = new Map(units.map(p => [p.Code, p]));
validateRemap();

const workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'goroute-geo-'));
fs.mkdirSync(path.dirname(outPath), { recursive: true });
const out = fs.createWriteStream(outPath, { encoding: 'utf8' });
const write = line => out.write(line + '\n');

write('-- Generated by goroute/scripts/geo/build_geo_sql.mjs -- do not edit by hand.');
write(`-- Dataset ${datasetVersion} (${metadata.LatestDecree}), generated ${metadata.GeneratedAt}.`);
write('-- Requires V170__geo_boundaries.sql. Safe to re-run: every statement upserts.');
write('BEGIN;');
write('SET LOCAL synchronous_commit = off;');
write(`INSERT INTO geo_dataset_versions (version, decree, generated_at, province_count, ward_count)
VALUES (${lit(datasetVersion)}, ${lit(metadata.LatestDecree)}, ${lit(metadata.GeneratedAt)}, ${units.length}, ${units.reduce((a, p) => a + p.Wards.length, 0)})
ON CONFLICT (version) DO UPDATE SET decree = EXCLUDED.decree, generated_at = EXCLUDED.generated_at,
  imported_at = now(), province_count = EXCLUDED.province_count, ward_count = EXCLUDED.ward_count;`);

const provinceDirs = fs.readdirSync(geojsonDir).filter(name => /^\d{2}_/.test(name));
let wardCount = 0;
for (const province of units) {
  const dir = provinceDirs.find(name => name.startsWith(province.Code + '_'));
  if (!dir) fail(`no geojson directory for province ${province.Code} ${province.Name}`);
  const provinceFile = path.join(geojsonDir, dir, `${dir}.geojson`);
  const wardsDir = path.join(geojsonDir, dir, 'wards');
  process.stderr.write(`province ${province.Code} ${province.Name} (${province.Wards.length} wards)\n`);

  const provinceFull = runMapshaper([provinceFile, '-o', 'precision=0.000001', 'format=geojson']);
  const provinceDisplay = runMapshaper([provinceFile, '-simplify', 'visvalingam', `interval=${PROVINCE_DISPLAY_INTERVAL}`, 'keep-shapes',
    '-o', 'precision=0.00001', 'format=geojson']);
  const oldRows = remap.old.filter(row => row.newCode === province.Code);
  const region = oldRows.find(row => row.code === province.Code)?.region
    || oldRows[0]?.region
    || fail(`no region for province ${province.Code}`);
  write(provinceInsert(province, region, oldRows, singleGeometry(provinceFull), singleGeometry(provinceDisplay)));

  const wardFiles = fs.readdirSync(wardsDir).filter(name => name.endsWith('.geojson')).map(name => path.join(wardsDir, name));
  if (wardFiles.length !== province.Wards.length) {
    fail(`province ${province.Code}: ${wardFiles.length} ward files but ${province.Wards.length} wards in units json`);
  }
  const wardsFull = runMapshaper([...wardFiles, 'combine-files', '-merge-layers', '-o', 'precision=0.000001', 'format=geojson']);
  const wardsDisplay = runMapshaper([...wardFiles, 'combine-files', '-merge-layers', '-simplify', 'visvalingam',
    `interval=${WARD_DISPLAY_INTERVAL}`, 'keep-shapes', '-o', 'precision=0.00001', 'format=geojson']);
  const fullByCode = byCode(wardsFull);
  const displayByCode = byCode(wardsDisplay);
  for (const ward of province.Wards) {
    const full = fullByCode.get(ward.Code) || fail(`ward ${ward.Code} missing from full geometry`);
    const display = displayByCode.get(ward.Code) || fail(`ward ${ward.Code} missing from display geometry`);
    write(wardInsert(ward, province.Code, full, display));
    wardCount++;
  }
}

write(`UPDATE provinces SET latitude = ST_Y(ST_PointOnSurface(geom)), longitude = ST_X(ST_PointOnSurface(geom)),
  bbox = ST_Envelope(geom) WHERE dataset_version = ${lit(datasetVersion)};`);
for (const row of remap.old) {
  write(`INSERT INTO province_code_remap (old_code, new_code, old_name) VALUES (${lit(row.code)}, ${lit(row.newCode)}, ${lit(row.name)})
ON CONFLICT (old_code) DO UPDATE SET new_code = EXCLUDED.new_code, old_name = EXCLUDED.old_name;`);
}
write('COMMIT;');
write('ANALYZE provinces;');
write('ANALYZE wards;');
out.end(() => {
  fs.rmSync(workDir, { recursive: true, force: true });
  process.stderr.write(`wrote ${outPath}: ${units.length} provinces, ${wardCount} wards\n`);
});

// ---------------------------------------------------------------------------

function provinceInsert(province, region, oldRows, geomFull, geomDisplay) {
  const aliases = new Set();
  addNameAliases(aliases, province.Name, province.FullName);
  for (const old of oldRows) addNameAliases(aliases, old.name, null);
  return `INSERT INTO provinces (code, name, normalized_name, region, aliases, dataset_version, is_active,
  name_en, full_name, full_name_en, code_name, area_km2, geom, geom_display)
VALUES (${lit(province.Code)}, ${lit(province.Name)}, ${lit(normalize(province.Name))}, ${lit(region)},
  ${lit(JSON.stringify([...aliases]))}::jsonb, ${lit(datasetVersion)}, TRUE,
  ${lit(province.NameEn)}, ${lit(province.FullName)}, ${lit(province.FullNameEn)}, ${lit(province.CodeName)},
  ${areaKm2(geomFull)}, ${geomLit(geomFull.geometry)}, ${geomLit(geomDisplay.geometry)})
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, normalized_name = EXCLUDED.normalized_name,
  region = EXCLUDED.region, aliases = EXCLUDED.aliases, dataset_version = EXCLUDED.dataset_version,
  is_active = TRUE, name_en = EXCLUDED.name_en, full_name = EXCLUDED.full_name,
  full_name_en = EXCLUDED.full_name_en, code_name = EXCLUDED.code_name, area_km2 = EXCLUDED.area_km2,
  geom = EXCLUDED.geom, geom_display = EXCLUDED.geom_display;`;
}

function wardInsert(ward, provinceCode, full, display) {
  return `INSERT INTO wards (code, province_code, name, name_en, full_name, full_name_en, code_name, unit_type,
  postal_code, area_km2, dataset_version, is_active, geom, geom_display)
VALUES (${lit(ward.Code)}, ${lit(provinceCode)}, ${lit(ward.Name)}, ${lit(ward.NameEn)}, ${lit(ward.FullName)},
  ${lit(ward.FullNameEn)}, ${lit(ward.CodeName)}, ${lit(unitType(ward))}, ${lit(ward.PostalCode || null)},
  ${areaKm2(full)}, ${lit(datasetVersion)}, TRUE, ${geomLit(full.geometry)}, ${geomLit(display.geometry)})
ON CONFLICT (code) DO UPDATE SET province_code = EXCLUDED.province_code, name = EXCLUDED.name,
  name_en = EXCLUDED.name_en, full_name = EXCLUDED.full_name, full_name_en = EXCLUDED.full_name_en,
  code_name = EXCLUDED.code_name, unit_type = EXCLUDED.unit_type, postal_code = EXCLUDED.postal_code,
  area_km2 = EXCLUDED.area_km2, dataset_version = EXCLUDED.dataset_version, is_active = TRUE,
  geom = EXCLUDED.geom, geom_display = EXCLUDED.geom_display;`;
}

function unitType(ward) {
  const short = (ward.AdministrativeUnitShortName || '').toLowerCase();
  if (short.startsWith('phường')) return 'WARD';
  if (short.startsWith('xã')) return 'COMMUNE';
  if (short.startsWith('đặc khu')) return 'SPECIAL_ZONE';
  fail(`unknown administrative unit '${ward.AdministrativeUnitShortName}' on ward ${ward.Code}`);
}

function geomLit(geometry) {
  // ST_MakeValid: a handful of source rings self-touch; ST_Covers refuses invalid input.
  return `ST_Multi(ST_CollectionExtract(ST_MakeValid(ST_SetSRID(ST_GeomFromGeoJSON(${dollar(JSON.stringify(geometry))}), 4326)), 3))`;
}

function areaKm2(feature) {
  const value = feature.properties?.areaKm2;
  return value == null ? 'NULL' : Number(value);
}

function addNameAliases(set, name, fullName) {
  const base = normalize(name);
  set.add(base);
  set.add('tinh ' + base);
  set.add('thanh pho ' + base);
  set.add('tp ' + base);
  if (fullName) set.add(normalize(fullName));
}

function normalize(value) {
  return String(value)
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/đ/g, 'd').replace(/Đ/g, 'D')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function singleGeometry(collection) {
  if (collection.features?.length !== 1) fail('expected exactly one province feature');
  return collection.features[0];
}

function byCode(collection) {
  const map = new Map();
  for (const feature of collection.features || []) map.set(feature.properties?.code, feature);
  return map;
}

function runMapshaper(mapshaperArgs) {
  const target = path.join(workDir, `out-${process.hrtime.bigint()}.geojson`);
  execFileSync(mapshaperCmd, [...mapshaperPrefix, ...mapshaperArgs, target], {
    stdio: ['ignore', 'ignore', 'inherit'],
    shell: !mapshaperBin && process.platform === 'win32',
    maxBuffer: 1024 * 1024 * 64,
    env: { ...process.env, NODE_OPTIONS: '--max-old-space-size=4096' },
  });
  const parsed = JSON.parse(fs.readFileSync(target, 'utf8'));
  fs.rmSync(target, { force: true });
  return parsed;
}

function validateRemap() {
  const newCodes = new Set(units.map(p => p.Code));
  const oldCodes = new Set();
  for (const row of remap.old) {
    if (oldCodes.has(row.code)) fail(`remap: duplicate old code ${row.code}`);
    oldCodes.add(row.code);
    if (!newCodes.has(row.newCode)) fail(`remap: old ${row.code} ${row.name} -> ${row.newCode}, which is not in the dataset`);
  }
  if (oldCodes.size !== 63) fail(`remap: expected 63 old codes, found ${oldCodes.size}`);
  for (const code of newCodes) {
    if (!remap.old.some(row => row.newCode === code)) fail(`remap: dataset province ${code} has no old code mapping to it`);
  }
}

function lit(value) {
  if (value == null) return 'NULL';
  return "'" + String(value).replace(/'/g, "''") + "'";
}

function dollar(value) {
  const tag = '$geo$';
  if (value.includes(tag)) fail('geometry text contains the dollar-quote tag');
  return tag + value + tag;
}

function parseArgs(argv) {
  const result = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) result[argv[i].slice(2)] = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : true;
  }
  return result;
}

function required(name) {
  return args[name] || fail(`--${name} is required`);
}

function fail(message) {
  process.stderr.write(message + '\n');
  process.exit(1);
}
