package com.ds.goroute.service.impl;

import com.ds.goroute.constant.ErrorConstant;
import com.ds.goroute.dto.request.*;
import com.ds.goroute.dto.response.*;
import com.ds.goroute.entity.*;
import com.ds.goroute.exception.BusinessException;
import com.ds.goroute.repository.ActivityCommerceRepository;
import com.ds.goroute.repository.HostOrganizationRepository;
import com.ds.goroute.repository.PlaceRepository;
import com.ds.goroute.mapper.AdminMapper;
import com.ds.goroute.service.ActivityCommerceService;
import com.ds.goroute.service.MarketplaceHistoryService;
import com.ds.goroute.service.PartnerAuthorizationService;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service @RequiredArgsConstructor
public class ActivityCommerceServiceImpl implements ActivityCommerceService {
 private static final Set<String> CANCELLED=Set.of("EXPIRED","FAILED","CANCELLED_BY_GUEST","CANCELLED_BY_HOST","CANCELLED_BY_PLATFORM");
 private final ActivityCommerceRepository repository;private final PlaceRepository placeRepository;private final HostOrganizationRepository organizationRepository;private final PartnerAuthorizationService authorization;
 private final MarketplaceHistoryService history;private final ObjectMapper objectMapper;
 private final AdminMapper adminMapper;

 public List<MarketplaceActivityResponse> listPublic(String q,int p,int s){Page r=page(p,s);return repository.findProductsPublic(clean(q),r.limit,r.offset).stream().map(this::productResponse).toList();}
 public MarketplaceActivityResponse getPublic(UUID id){MarketplaceActivityProduct p=product(id);if(!"ENABLED".equals(p.getProductStatus())||!organizationBookable(p.getOrganizationId()))throw notFound("Activity not found");return productResponse(p);}
 public List<ActivityPackageResponse> listPublicPackages(UUID id){getPublic(id);return repository.findPackages(id,false).stream().map(this::packageResponse).toList();}
 public List<ActivitySlotResponse> listPublicSlots(UUID id,LocalDateTime from){ActivityPackage p=pack(id);getPublic(p.getActivityBookingId());if(!"ENABLED".equals(p.getStatus()))throw notFound("Package not found");return repository.findSlots(id,from==null?LocalDateTime.now():from,false).stream().map(this::slotResponse).toList();}
 public List<MarketplaceActivityResponse> partnerList(UUID actor,UUID org){authorization.requireOrganization(org,actor);return repository.findProductsByOrganization(org).stream().filter(p->authorization.hasResourcePermission(org,actor,"ACTIVITY",p.getId(),"ACTIVITY_READ")).map(this::productResponse).toList();}

 @Transactional public MarketplaceActivityResponse partnerCreate(UUID actor,UpsertMarketplaceActivityRequest r){authorization.requirePermission(r.getOrganizationId(),actor,"ACTIVITY_WRITE");if(r.getPlaceId()!=null)placeRepository.findById(r.getPlaceId()).orElseThrow(()->new BusinessException(ErrorConstant.PLACE_NOT_FOUND));currency(r.getPriceCurrency());LocalDateTime now=LocalDateTime.now();MarketplaceActivityProduct p=MarketplaceActivityProduct.builder().id(UUID.randomUUID()).organizationId(r.getOrganizationId()).placeId(r.getPlaceId()).source("GOROUTE").title(r.getTitle().trim()).description(clean(r.getDescription())).activityAddress(clean(r.getActivityAddress())).priceAmount(r.getPriceAmount()).priceCurrency(r.getPriceCurrency().toUpperCase()).durationRaw(clean(r.getDurationRaw())).durationHours(r.getDurationHours()).visitDurationMinutes(r.getVisitDurationMinutes()).thumbnail(clean(r.getThumbnail())).images(json(list(r.getImages()))).highlights(json(list(r.getHighlights()))).productStatus(def(r.getProductStatus(),"DRAFT")).inventoryMode("INTERNAL").dataVersion(1L).createdBy(actor).updatedBy(actor).createdAt(now).updatedAt(now).build();repository.insertProduct(p);history.record(p.getOrganizationId(),"ACTIVITY_PRODUCT",p.getId(),"CREATED",p,List.of(),actor,actorType(actor),null);return productResponse(repository.findProduct(p.getId()).orElse(p));}
 @Transactional public MarketplaceActivityResponse partnerUpdate(UUID actor,UUID id,UpsertMarketplaceActivityRequest r){MarketplaceActivityProduct p=product(id);authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_WRITE");if("SUSPENDED".equals(p.getProductStatus()))throw new BusinessException(ErrorConstant.FORBIDDEN_ERROR,"A suspended activity can only be changed by an admin");if(!p.getOrganizationId().equals(r.getOrganizationId())||!Objects.equals(p.getPlaceId(),r.getPlaceId()))throw bad("organizationId and placeId are immutable");currency(r.getPriceCurrency());long v=version(r.getExpectedVersion(),p.getDataVersion());p.setTitle(r.getTitle().trim());p.setDescription(clean(r.getDescription()));p.setActivityAddress(clean(r.getActivityAddress()));p.setPriceAmount(r.getPriceAmount());p.setPriceCurrency(r.getPriceCurrency().toUpperCase());p.setDurationRaw(clean(r.getDurationRaw()));p.setDurationHours(r.getDurationHours());p.setVisitDurationMinutes(r.getVisitDurationMinutes());p.setThumbnail(clean(r.getThumbnail()));p.setImages(json(list(r.getImages())));p.setHighlights(json(list(r.getHighlights())));p.setProductStatus(def(r.getProductStatus(),p.getProductStatus()));p.setDataVersion(v);p.setUpdatedBy(actor);p.setUpdatedAt(LocalDateTime.now());optimistic(repository.updateProduct(p),"Activity");p.setDataVersion(v+1);history.record(p.getOrganizationId(),"ACTIVITY_PRODUCT",id,"UPDATED",p,List.of("PROFILE"),actor,"USER",null);return productResponse(repository.findProduct(id).orElse(p));}
 public List<ActivityPackageResponse> partnerPackages(UUID actor,UUID id){MarketplaceActivityProduct p=product(id);authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_READ");return repository.findPackages(id,true).stream().map(this::packageResponse).toList();}

 @Transactional public ActivityPackageResponse partnerCreatePackage(UUID actor,UUID id,UpsertActivityPackageRequest r){MarketplaceActivityProduct p=product(id);authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_WRITE");validatePackage(r);LocalDateTime n=LocalDateTime.now();ActivityPackage v=ActivityPackage.builder().id(UUID.randomUUID()).activityBookingId(id).code(code(r.getCode())).name(r.getName().trim()).description(clean(r.getDescription())).currency(r.getCurrency().toUpperCase()).basePrice(r.getBasePrice()).minQuantity(r.getMinQuantity()).maxQuantity(r.getMaxQuantity()).attributes(json(map(r.getAttributes()))).cancellationPolicy(json(map(r.getCancellationPolicy()))).status(def(r.getStatus(),"ENABLED")).dataVersion(1L).createdBy(actor).updatedBy(actor).createdAt(n).updatedAt(n).build();try{repository.insertPackage(v);}catch(DataIntegrityViolationException ex){throw conflict("Package code already exists");}history.record(p.getOrganizationId(),"ACTIVITY_PACKAGE",v.getId(),"CREATED",v,List.of(),actor,"USER",null);return packageResponse(v);}
 @Transactional public ActivityPackageResponse partnerUpdatePackage(UUID actor,UUID id,UpsertActivityPackageRequest r){ActivityPackage v=pack(id);MarketplaceActivityProduct p=product(v.getActivityBookingId());authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_WRITE");validatePackage(r);long ver=version(r.getExpectedVersion(),v.getDataVersion());v.setCode(code(r.getCode()));v.setName(r.getName().trim());v.setDescription(clean(r.getDescription()));v.setCurrency(r.getCurrency().toUpperCase());v.setBasePrice(r.getBasePrice());v.setMinQuantity(r.getMinQuantity());v.setMaxQuantity(r.getMaxQuantity());v.setAttributes(json(map(r.getAttributes())));v.setCancellationPolicy(json(map(r.getCancellationPolicy())));v.setStatus(def(r.getStatus(),v.getStatus()));v.setDataVersion(ver);v.setUpdatedBy(actor);v.setUpdatedAt(LocalDateTime.now());try{optimistic(repository.updatePackage(v),"Package");}catch(DataIntegrityViolationException ex){throw conflict("Package update violates code or quantity constraints");}v.setDataVersion(ver+1);history.record(p.getOrganizationId(),"ACTIVITY_PACKAGE",id,"UPDATED",v,List.of("PACKAGE"),actor,"USER",null);return packageResponse(v);}
 public List<ActivitySlotResponse> partnerSlots(UUID actor,UUID id,LocalDateTime from){ActivityPackage a=pack(id);MarketplaceActivityProduct p=product(a.getActivityBookingId());authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_READ");return repository.findSlots(id,from==null?LocalDateTime.now().minusYears(1):from,true).stream().map(this::slotResponse).toList();}

 @Transactional public ActivitySlotResponse partnerCreateSlot(UUID actor,UUID id,UpsertActivitySlotRequest r){ActivityPackage a=pack(id);MarketplaceActivityProduct p=product(a.getActivityBookingId());authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"SLOT_WRITE");validateSlot(r);LocalDateTime n=LocalDateTime.now();ActivitySlot s=ActivitySlot.builder().id(UUID.randomUUID()).packageId(id).startsAt(r.getStartsAt()).endsAt(r.getEndsAt()).timezone(r.getTimezone()).capacity(r.getCapacity()).reservedQuantity(0).soldQuantity(0).blockedQuantity(r.getBlockedQuantity()).bookingCutoffMinutes(r.getBookingCutoffMinutes()).priceOverride(r.getPriceOverride()).status(def(r.getStatus(),"ENABLED")).dataVersion(1L).updatedBy(actor).createdAt(n).updatedAt(n).build();repository.insertSlot(s);history.record(p.getOrganizationId(),"ACTIVITY_SLOT",s.getId(),"CREATED",s,List.of(),actor,"USER",null);return slotResponse(repository.findSlot(s.getId()).orElse(s));}
 @Transactional public ActivitySlotResponse partnerUpdateSlot(UUID actor,UUID id,UpsertActivitySlotRequest r){ActivitySlot s=slot(id);ActivityPackage a=pack(s.getPackageId());MarketplaceActivityProduct p=product(a.getActivityBookingId());authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"SLOT_WRITE");validateSlot(r);long v=version(r.getExpectedVersion(),s.getDataVersion());s.setStartsAt(r.getStartsAt());s.setEndsAt(r.getEndsAt());s.setTimezone(r.getTimezone());s.setCapacity(r.getCapacity());s.setBlockedQuantity(r.getBlockedQuantity());s.setBookingCutoffMinutes(r.getBookingCutoffMinutes());s.setPriceOverride(r.getPriceOverride());s.setStatus(def(r.getStatus(),s.getStatus()));s.setDataVersion(v);s.setUpdatedBy(actor);s.setUpdatedAt(LocalDateTime.now());optimistic(repository.updateSlot(s),"Slot");s.setDataVersion(v+1);history.record(p.getOrganizationId(),"ACTIVITY_SLOT",id,"UPDATED",s,List.of("SCHEDULE","CAPACITY"),actor,"USER",null);return slotResponse(repository.findSlot(id).orElse(s));}

 @Transactional public ActivityOrderResponse createOrder(UUID user,CreateActivityOrderRequest r){MarketplaceActivityProduct p=product(r.getActivityId());ActivityPackage a=pack(r.getPackageId());ActivitySlot s=slot(r.getSlotId());if(!organizationBookable(p.getOrganizationId())||!"ENABLED".equals(p.getProductStatus())||!"ENABLED".equals(a.getStatus())||!"ENABLED".equals(s.getStatus())||!a.getActivityBookingId().equals(p.getId())||!s.getPackageId().equals(a.getId()))throw notFound("Bookable activity option not found");int q=r.getQuantity();if(q<a.getMinQuantity()||a.getMaxQuantity()!=null&&q>a.getMaxQuantity())throw bad("Quantity is outside package limits");BigDecimal unit=s.getPriceOverride()==null?a.getBasePrice():s.getPriceOverride();BigDecimal total=unit.multiply(BigDecimal.valueOf(q));LocalDateTime n=LocalDateTime.now();if(repository.reserveSlot(s.getId(),q,user,n)!=1)throw conflict("Activity slot is no longer available");Map<String,Object> snap=new LinkedHashMap<>();snap.put("activity",p);snap.put("package",a);snap.put("slot",s);ActivityOrder o=ActivityOrder.builder().id(UUID.randomUUID()).orderCode(orderCode()).userId(user).organizationId(p.getOrganizationId()).activityBookingId(p.getId()).slotId(s.getId()).participantInfo(json(list(r.getParticipants()))).currency(a.getCurrency()).subtotalAmount(total).taxAmount(BigDecimal.ZERO).feeAmount(BigDecimal.ZERO).discountAmount(BigDecimal.ZERO).totalAmount(total).orderStatus("PENDING_PAYMENT").paymentStatus("UNPAID").snapshot(json(snap)).dataVersion(1L).createdBy(user).updatedBy(user).createdAt(n).updatedAt(n).build();ActivityOrderItem i=ActivityOrderItem.builder().id(UUID.randomUUID()).orderId(o.getId()).packageId(a.getId()).quantity(q).unitPrice(unit).totalPrice(total).snapshot(json(snap)).createdAt(n).build();repository.insertOrder(o);repository.insertOrderItem(i);history.record(p.getOrganizationId(),"ACTIVITY_ORDER",o.getId(),"CREATED",o,List.of(),user,"USER",null);return orderResponse(repository.findOrder(o.getId()).orElse(o));}
 public List<ActivityOrderResponse> listMyOrders(UUID u,int p,int s){Page r=page(p,s);return repository.findOrdersByUser(u,r.limit,r.offset).stream().map(this::orderResponse).toList();}
 public ActivityOrderResponse getMyOrder(UUID u,UUID id){ActivityOrder o=order(id);if(!u.equals(o.getUserId()))throw forbidden();return orderResponse(o);}
 @Transactional public ActivityOrderResponse cancelMyOrder(UUID u,UUID id,String reason,Long v){ActivityOrder o=order(id);if(!u.equals(o.getUserId()))throw forbidden();return transition(o,"CANCELLED_BY_GUEST",reason,v,u,"USER");}
 public List<ActivityOrderResponse> partnerOrders(UUID a,UUID org,String status,int p,int s){authorization.requireOrganization(org,a);Page r=page(p,s);return repository.findOrdersByOrganization(org,clean(status),r.limit,r.offset).stream().filter(o->authorization.hasResourcePermission(org,a,"ACTIVITY",o.getActivityBookingId(),"ORDER_READ")).map(this::orderResponse).toList();}
 public ActivityOrderResponse partnerOrder(UUID a,UUID id){ActivityOrder o=order(id);authorization.requireResourcePermission(o.getOrganizationId(),a,"ACTIVITY",o.getActivityBookingId(),"ORDER_READ");return orderResponse(o);}
 @Transactional public ActivityOrderResponse partnerOrderStatus(UUID a,UUID id,UpdateActivityOrderStatusRequest r){ActivityOrder o=order(id);authorization.requireResourcePermission(o.getOrganizationId(),a,"ACTIVITY",o.getActivityBookingId(),"ORDER_WRITE");return transition(o,r.getOrderStatus(),r.getReason(),r.getExpectedVersion(),a,"USER");}
 public List<MarketplaceActivityResponse> adminProducts(String q,String s,int p,int z){Page r=page(p,z);return repository.findProductsAdmin(clean(q),clean(s),r.limit,r.offset).stream().map(this::productResponse).toList();}
 public MarketplaceActivityResponse adminProduct(UUID id){return productResponse(product(id));}
 public List<ActivityPackageResponse> adminPackages(UUID id){product(id);return repository.findPackages(id,true).stream().map(this::packageResponse).toList();}
 public List<ActivitySlotResponse> adminSlots(UUID id,LocalDateTime from){pack(id);return repository.findSlots(id,from==null?LocalDateTime.now().minusYears(1):from,true).stream().map(this::slotResponse).toList();}
 public ActivityOrderResponse adminOrder(UUID id){return orderResponse(order(id));}
 @Transactional public MarketplaceActivityResponse adminProductStatus(UUID id,String status,String reason){if(!Set.of("ENABLED","DISABLED","ARCHIVED","SUSPENDED").contains(status))throw bad("Invalid status");MarketplaceActivityProduct p=product(id);p.setProductStatus(status);p.setUpdatedBy(null);p.setUpdatedAt(LocalDateTime.now());optimistic(repository.updateProduct(p),"Activity");p.setDataVersion(p.getDataVersion()+1);history.record(p.getOrganizationId(),"ACTIVITY_PRODUCT",id,"ADMIN_STATUS_CHANGED",p,List.of("productStatus"),null,"ADMIN",reason);return productResponse(repository.findProduct(id).orElse(p));}
 public List<ActivityOrderResponse> adminOrders(String q,String s,int p,int z){Page r=page(p,z);return repository.findOrdersAdmin(clean(q),clean(s),r.limit,r.offset).stream().map(this::orderResponse).toList();}
 @Transactional public ActivityOrderResponse adminOrderStatus(UUID id,UpdateActivityOrderStatusRequest r){return transition(order(id),r.getOrderStatus(),r.getReason(),r.getExpectedVersion(),null,"ADMIN");}
 public MarketplaceActivityResponse adminCreateProduct(UUID actor,UpsertMarketplaceActivityRequest r){return partnerCreate(actor,r);}public MarketplaceActivityResponse adminUpdateProduct(UUID actor,UUID id,UpsertMarketplaceActivityRequest r){MarketplaceActivityProduct current=product(id);if("SUSPENDED".equals(current.getProductStatus())){adminProductStatus(id,"DISABLED","Admin editing suspended activity");r.setExpectedVersion(product(id).getDataVersion());}return partnerUpdate(actor,id,r);}
 public ActivityPackageResponse adminCreatePackage(UUID actor,UUID activityId,UpsertActivityPackageRequest r){return partnerCreatePackage(actor,activityId,r);}public ActivityPackageResponse adminUpdatePackage(UUID actor,UUID id,UpsertActivityPackageRequest r){return partnerUpdatePackage(actor,id,r);}
 public ActivitySlotResponse adminCreateSlot(UUID actor,UUID packageId,UpsertActivitySlotRequest r){return partnerCreateSlot(actor,packageId,r);}public ActivitySlotResponse adminUpdateSlot(UUID actor,UUID id,UpsertActivitySlotRequest r){return partnerUpdateSlot(actor,id,r);}

 private ActivityOrderResponse transition(ActivityOrder o,String target,String reason,Long requested,UUID actor,String type){Map<String,Set<String>> allowed=Map.of("PENDING_PAYMENT",Set.of("CONFIRMED","EXPIRED","FAILED","CANCELLED_BY_GUEST","CANCELLED_BY_HOST","CANCELLED_BY_PLATFORM"),"CONFIRMED",Set.of("CHECKED_IN","COMPLETED","NO_SHOW","CANCELLED_BY_GUEST","CANCELLED_BY_HOST","CANCELLED_BY_PLATFORM"),"CHECKED_IN",Set.of("COMPLETED"));if(!allowed.getOrDefault(o.getOrderStatus(),Set.of()).contains(target))throw bad("Invalid order transition: "+o.getOrderStatus()+" -> "+target);ActivityOrderItem i=repository.findOrderItem(o.getId()).orElseThrow(()->notFound("Order item not found"));if("CONFIRMED".equals(target)){if(repository.confirmSlot(o.getSlotId(),i.getQuantity(),actor,LocalDateTime.now())!=1)throw conflict("Reserved slot inventory is inconsistent");}else if(CANCELLED.contains(target)){boolean reserved="PENDING_PAYMENT".equals(o.getOrderStatus());if(repository.releaseSlot(o.getSlotId(),i.getQuantity(),reserved,actor,LocalDateTime.now())!=1)throw conflict("Allocated slot inventory is inconsistent");}optimistic(repository.updateOrderStatus(o.getId(),version(requested,o.getDataVersion()),target,actor,LocalDateTime.now()),"Activity order");ActivityOrder saved=order(o.getId());history.record(saved.getOrganizationId(),"ACTIVITY_ORDER",saved.getId(),"STATUS_CHANGED",saved,List.of("orderStatus"),actor,type,reason);return orderResponse(saved);}
 private MarketplaceActivityResponse productResponse(MarketplaceActivityProduct p){return MarketplaceActivityResponse.builder().id(p.getId()).organizationId(p.getOrganizationId()).placeId(p.getPlaceId()).placeTitle(p.getPlaceTitle()).title(p.getTitle()).description(p.getDescription()).activityAddress(p.getActivityAddress()).priceAmount(p.getPriceAmount()).priceCurrency(p.getPriceCurrency()).durationRaw(p.getDurationRaw()).durationHours(p.getDurationHours()).visitDurationMinutes(p.getVisitDurationMinutes()).thumbnail(p.getThumbnail()).images(readList(p.getImages(),String.class)).highlights(readList(p.getHighlights(),String.class)).productStatus(p.getProductStatus()).inventoryMode(p.getInventoryMode()).dataVersion(p.getDataVersion()).createdAt(p.getCreatedAt()).updatedAt(p.getUpdatedAt()).build();}
 private ActivityPackageResponse packageResponse(ActivityPackage a){return ActivityPackageResponse.builder().id(a.getId()).activityId(a.getActivityBookingId()).code(a.getCode()).name(a.getName()).description(a.getDescription()).currency(a.getCurrency()).basePrice(a.getBasePrice()).minQuantity(a.getMinQuantity()).maxQuantity(a.getMaxQuantity()).attributes(readMap(a.getAttributes())).cancellationPolicy(readMap(a.getCancellationPolicy())).status(a.getStatus()).dataVersion(a.getDataVersion()).createdAt(a.getCreatedAt()).updatedAt(a.getUpdatedAt()).build();}
 private ActivitySlotResponse slotResponse(ActivitySlot s){return ActivitySlotResponse.builder().id(s.getId()).packageId(s.getPackageId()).startsAt(s.getStartsAt()).endsAt(s.getEndsAt()).timezone(s.getTimezone()).capacity(s.getCapacity()).reservedQuantity(s.getReservedQuantity()).soldQuantity(s.getSoldQuantity()).blockedQuantity(s.getBlockedQuantity()).availableQuantity(s.getAvailableQuantity()).bookingCutoffMinutes(s.getBookingCutoffMinutes()).priceOverride(s.getPriceOverride()).status(s.getStatus()).dataVersion(s.getDataVersion()).createdAt(s.getCreatedAt()).updatedAt(s.getUpdatedAt()).build();}
 private ActivityOrderResponse orderResponse(ActivityOrder o){ActivityOrderItem i=repository.findOrderItem(o.getId()).orElse(null);ActivityOrderItemResponse ir=i==null?null:ActivityOrderItemResponse.builder().id(i.getId()).packageId(i.getPackageId()).packageName(i.getPackageName()).quantity(i.getQuantity()).unitPrice(i.getUnitPrice()).totalPrice(i.getTotalPrice()).snapshot(readMap(i.getSnapshot())).build();return ActivityOrderResponse.builder().id(o.getId()).orderCode(o.getOrderCode()).userId(o.getUserId()).organizationId(o.getOrganizationId()).activityId(o.getActivityBookingId()).activityTitle(o.getActivityTitle()).slotId(o.getSlotId()).participants(readValue(o.getParticipantInfo(),new TypeReference<List<Map<String,Object>>>(){},List.of())).currency(o.getCurrency()).subtotalAmount(o.getSubtotalAmount()).taxAmount(o.getTaxAmount()).feeAmount(o.getFeeAmount()).discountAmount(o.getDiscountAmount()).totalAmount(o.getTotalAmount()).orderStatus(o.getOrderStatus()).paymentStatus(o.getPaymentStatus()).voucherCode(o.getVoucherCode()).dataVersion(o.getDataVersion()).item(ir).createdAt(o.getCreatedAt()).updatedAt(o.getUpdatedAt()).build();}
 private MarketplaceActivityProduct product(UUID id){return repository.findProduct(id).orElseThrow(()->notFound("Activity not found"));}private ActivityPackage pack(UUID id){return repository.findPackage(id).orElseThrow(()->notFound("Package not found"));}private ActivitySlot slot(UUID id){return repository.findSlot(id).orElseThrow(()->notFound("Slot not found"));}private ActivityOrder order(UUID id){return repository.findOrder(id).orElseThrow(()->notFound("Activity order not found"));}
 private boolean organizationBookable(UUID organizationId){return organizationId!=null&&organizationRepository.findById(organizationId).map(o->"ENABLED".equals(o.getOperationalStatus())&&!"SUSPENDED".equals(o.getVerificationStatus())).orElse(false);}
 private void validatePackage(UpsertActivityPackageRequest r){currency(r.getCurrency());if(r.getMaxQuantity()!=null&&r.getMaxQuantity()<r.getMinQuantity())throw bad("maxQuantity must be >= minQuantity");}private void validateSlot(UpsertActivitySlotRequest r){try{ZoneId.of(r.getTimezone());}catch(Exception e){throw bad("Invalid IANA timezone");}if(r.getEndsAt()!=null&&!r.getEndsAt().isAfter(r.getStartsAt()))throw bad("endsAt must be after startsAt");if(r.getBlockedQuantity()>r.getCapacity())throw bad("blockedQuantity exceeds capacity");}private void currency(String v){try{Currency.getInstance(v);}catch(Exception e){throw bad("Invalid currency");}}
 private long version(Long v,Long current){return v==null?current:v;}private void optimistic(int n,String x){if(n!=1)throw conflict(x+" was changed or violates allocated inventory");}private String orderCode(){return "ACT-"+LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE)+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();}private String code(String s){return s.trim().toUpperCase(Locale.ROOT);}private String clean(String s){return s==null||s.isBlank()?null:s.trim();}private String def(String s,String d){return s==null||s.isBlank()?d:s;}private <T>List<T> list(List<T> v){return v==null?List.of():v;}private <K,V>Map<K,V> map(Map<K,V> v){return v==null?Map.of():v;}
 private String actorType(UUID actor){return actor!=null&&adminMapper.hasAnyRole(actor)?"ADMIN":"USER";}
 private String json(Object v){try{return objectMapper.writeValueAsString(v);}catch(JsonProcessingException e){throw new BusinessException(ErrorConstant.INTERNAL_SERVER_ERROR,"Cannot serialize activity data");}}private Map<String,Object> readMap(String v){return readValue(v,new TypeReference<Map<String,Object>>(){},Map.of());}private <T>List<T> readList(String v,Class<T> c){if(v==null)return List.of();try{return objectMapper.readValue(v,objectMapper.getTypeFactory().constructCollectionType(List.class,c));}catch(Exception e){return List.of();}}private <T>T readValue(String v,TypeReference<T> t,T f){if(v==null)return f;try{return objectMapper.readValue(v,t);}catch(Exception e){return f;}}
 private Page page(int p,int s){int l=Math.min(Math.max(s,1),200);return new Page(l,Math.max(p,0)*l);}private BusinessException bad(String m){return new BusinessException(ErrorConstant.BAD_REQUEST,m);}private BusinessException conflict(String m){return new BusinessException(ErrorConstant.ALREADY_PROCESSED,m);}private BusinessException notFound(String m){return new BusinessException(ErrorConstant.NOT_FOUND,m);}private BusinessException forbidden(){return new BusinessException(ErrorConstant.FORBIDDEN_ERROR,"You cannot access this activity order");}private record Page(int limit,int offset){}
}
