package com.ds.goroute.service.impl;

import com.ds.goroute.constant.ErrorConstant;
import com.ds.goroute.dto.GeoCoordinateDto;
import com.ds.goroute.dto.request.*;
import com.ds.goroute.dto.response.*;
import com.ds.goroute.entity.*;
import com.ds.goroute.exception.BusinessException;
import com.ds.goroute.repository.ActivityCommerceRepository;
import com.ds.goroute.repository.HostOrganizationRepository;
import com.ds.goroute.repository.PlaceRepository;
import com.ds.goroute.mapper.AdminMapper;
import com.ds.goroute.service.ActivityCommerceService;
import com.ds.goroute.service.MarketplaceHistoryService;
import com.ds.goroute.service.PartnerAuthorizationService;
import com.ds.goroute.type.MarketplaceAvailabilityStatus;
import com.ds.goroute.type.MarketplaceBookingStatus;
import com.ds.goroute.type.MarketplacePaymentStatus;
import com.ds.goroute.type.MarketplacePublicationStatus;
import com.ds.goroute.type.MarketplaceSlotStatus;
import com.ds.goroute.type.OrganizationOperationalStatus;
import com.ds.goroute.type.OrganizationVerificationStatus;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service @RequiredArgsConstructor
public class ActivityCommerceServiceImpl implements ActivityCommerceService {
 private final ActivityCommerceRepository repository;private final PlaceRepository placeRepository;private final HostOrganizationRepository organizationRepository;private final PartnerAuthorizationService authorization;
 private final MarketplaceHistoryService history;private final ObjectMapper objectMapper;
 private final AdminMapper adminMapper;

 public List<MarketplaceActivityResponse> listPublic(String q,int p,int s){Page r=page(p,s);return repository.findProductsPublic(clean(q),r.limit,r.offset).stream().map(this::productResponse).toList();}
 public MarketplaceActivityResponse getPublic(UUID id){return productResponse(publicProduct(id));}
 public List<ActivityPackageResponse> listPublicPackages(UUID id){getPublic(id);return repository.findPackages(id,false).stream().map(this::packageResponse).toList();}
 public List<ActivitySlotResponse> listPublicSlots(UUID id,LocalDateTime from){ActivityPackage p=pack(id);getPublic(p.getActivityBookingId());if(!MarketplaceAvailabilityStatus.ENABLED.name().equals(p.getStatus()))throw notFound("Package not found");return repository.findSlots(id,from==null?LocalDateTime.now():from,false).stream().map(this::slotResponse).toList();}
 public List<MarketplaceActivityResponse> partnerList(UUID actor,UUID org){authorization.requireOrganization(org,actor);return repository.findProductsByOrganization(org).stream().filter(p->authorization.hasResourcePermission(org,actor,"ACTIVITY",p.getId(),"ACTIVITY_READ")).map(this::productResponse).toList();}

 @Transactional public MarketplaceActivityResponse partnerCreate(UUID actor,UpsertMarketplaceActivityRequest r){authorization.requirePermission(r.getOrganizationId(),actor,"ACTIVITY_WRITE");if(r.getPlaceId()!=null)placeRepository.findById(r.getPlaceId()).orElseThrow(()->new BusinessException(ErrorConstant.PLACE_NOT_FOUND));currency(r.getPriceCurrency());LocalDateTime now=LocalDateTime.now();MarketplaceActivityProduct p=MarketplaceActivityProduct.builder().id(UUID.randomUUID()).organizationId(r.getOrganizationId()).placeId(r.getPlaceId()).source("GOROUTE").productStatus(partnerPublicationStatus(r.getProductStatus(),MarketplacePublicationStatus.DRAFT.name())).inventoryMode("INTERNAL").dataVersion(1L).createdBy(actor).updatedBy(actor).createdAt(now).updatedAt(now).build();applyProductDetails(p,r);repository.insertProduct(p);history.record(p.getOrganizationId(),"ACTIVITY_PRODUCT",p.getId(),"CREATED",p,List.of(),actor,actorType(actor),null);return productResponse(repository.findProduct(p.getId()).orElse(p));}
 @Transactional public MarketplaceActivityResponse partnerUpdate(UUID actor,UUID id,UpsertMarketplaceActivityRequest r){MarketplaceActivityProduct p=product(id);authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_WRITE");if(MarketplacePublicationStatus.SUSPENDED.name().equals(p.getProductStatus()))throw new BusinessException(ErrorConstant.FORBIDDEN_ERROR,"A suspended activity can only be changed by an admin");if(!p.getOrganizationId().equals(r.getOrganizationId())||!Objects.equals(p.getPlaceId(),r.getPlaceId()))throw bad("organizationId and placeId are immutable");currency(r.getPriceCurrency());long v=requiredVersion(r.getExpectedVersion());applyProductDetails(p,r);p.setProductStatus(partnerPublicationStatus(r.getProductStatus(),p.getProductStatus()));p.setDataVersion(v);p.setUpdatedBy(actor);p.setUpdatedAt(LocalDateTime.now());optimistic(repository.updateProduct(p),"Activity");p.setDataVersion(v+1);history.record(p.getOrganizationId(),"ACTIVITY_PRODUCT",id,"UPDATED",p,List.of("PROFILE","LOCATION","ITINERARY","MEDIA"),actor,"USER",null);return productResponse(repository.findProduct(id).orElse(p));}
 public List<ActivityPackageResponse> partnerPackages(UUID actor,UUID id){MarketplaceActivityProduct p=product(id);authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_READ");return repository.findPackages(id,true).stream().map(this::packageResponse).toList();}

 @Transactional public ActivityPackageResponse partnerCreatePackage(UUID actor,UUID id,UpsertActivityPackageRequest r){MarketplaceActivityProduct p=product(id);authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_WRITE");validatePackage(r);LocalDateTime n=LocalDateTime.now();ActivityPackage v=ActivityPackage.builder().id(UUID.randomUUID()).activityBookingId(id).code(code(r.getCode())).name(r.getName().trim()).description(clean(r.getDescription())).currency(r.getCurrency().toUpperCase()).basePrice(r.getBasePrice()).minQuantity(r.getMinQuantity()).maxQuantity(r.getMaxQuantity()).attributes(json(map(r.getAttributes()))).cancellationPolicy(json(map(r.getCancellationPolicy()))).status(enumNameOrDefault(r.getStatus(),MarketplaceAvailabilityStatus.ENABLED)).dataVersion(1L).createdBy(actor).updatedBy(actor).createdAt(n).updatedAt(n).build();try{repository.insertPackage(v);}catch(DataIntegrityViolationException ex){throw conflict("Package code already exists");}history.record(p.getOrganizationId(),"ACTIVITY_PACKAGE",v.getId(),"CREATED",v,List.of(),actor,"USER",null);return packageResponse(v);}
 @Transactional public ActivityPackageResponse partnerUpdatePackage(UUID actor,UUID id,UpsertActivityPackageRequest r){ActivityPackage v=pack(id);MarketplaceActivityProduct p=product(v.getActivityBookingId());authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_WRITE");validatePackage(r);long ver=requiredVersion(r.getExpectedVersion());v.setCode(code(r.getCode()));v.setName(r.getName().trim());v.setDescription(clean(r.getDescription()));v.setCurrency(r.getCurrency().toUpperCase());v.setBasePrice(r.getBasePrice());v.setMinQuantity(r.getMinQuantity());v.setMaxQuantity(r.getMaxQuantity());v.setAttributes(json(map(r.getAttributes())));v.setCancellationPolicy(json(map(r.getCancellationPolicy())));v.setStatus(enumNameOrDefault(r.getStatus(),v.getStatus()));v.setDataVersion(ver);v.setUpdatedBy(actor);v.setUpdatedAt(LocalDateTime.now());try{optimistic(repository.updatePackage(v),"Package");}catch(DataIntegrityViolationException ex){throw conflict("Package update violates code or quantity constraints");}v.setDataVersion(ver+1);history.record(p.getOrganizationId(),"ACTIVITY_PACKAGE",id,"UPDATED",v,List.of("PACKAGE"),actor,"USER",null);return packageResponse(v);}
 public List<ActivitySlotResponse> partnerSlots(UUID actor,UUID id,LocalDateTime from){ActivityPackage a=pack(id);MarketplaceActivityProduct p=product(a.getActivityBookingId());authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"ACTIVITY_READ");return repository.findSlots(id,from==null?LocalDateTime.now().minusYears(1):from,true).stream().map(this::slotResponse).toList();}

 @Transactional public ActivitySlotResponse partnerCreateSlot(UUID actor,UUID id,UpsertActivitySlotRequest r){ActivityPackage a=pack(id);MarketplaceActivityProduct p=product(a.getActivityBookingId());authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"SLOT_WRITE");validateSlot(r);LocalDateTime n=LocalDateTime.now();ActivitySlot s=ActivitySlot.builder().id(UUID.randomUUID()).packageId(id).startsAt(r.getStartsAt()).endsAt(r.getEndsAt()).timezone(r.getTimezone()).capacity(r.getCapacity()).reservedQuantity(0).soldQuantity(0).blockedQuantity(r.getBlockedQuantity()).bookingCutoffMinutes(r.getBookingCutoffMinutes()).priceOverride(r.getPriceOverride()).status(enumNameOrDefault(r.getStatus(),MarketplaceSlotStatus.ENABLED)).dataVersion(1L).updatedBy(actor).createdAt(n).updatedAt(n).build();repository.insertSlot(s);history.record(p.getOrganizationId(),"ACTIVITY_SLOT",s.getId(),"CREATED",s,List.of(),actor,"USER",null);return slotResponse(repository.findSlot(s.getId()).orElse(s));}
 @Transactional public ActivitySlotResponse partnerUpdateSlot(UUID actor,UUID id,UpsertActivitySlotRequest r){ActivitySlot s=slot(id);ActivityPackage a=pack(s.getPackageId());MarketplaceActivityProduct p=product(a.getActivityBookingId());authorization.requireResourcePermission(p.getOrganizationId(),actor,"ACTIVITY",p.getId(),"SLOT_WRITE");validateSlot(r);long v=requiredVersion(r.getExpectedVersion());s.setStartsAt(r.getStartsAt());s.setEndsAt(r.getEndsAt());s.setTimezone(r.getTimezone());s.setCapacity(r.getCapacity());s.setBlockedQuantity(r.getBlockedQuantity());s.setBookingCutoffMinutes(r.getBookingCutoffMinutes());s.setPriceOverride(r.getPriceOverride());s.setStatus(enumNameOrDefault(r.getStatus(),s.getStatus()));s.setDataVersion(v);s.setUpdatedBy(actor);s.setUpdatedAt(LocalDateTime.now());optimistic(repository.updateSlot(s),"Slot");s.setDataVersion(v+1);history.record(p.getOrganizationId(),"ACTIVITY_SLOT",id,"UPDATED",s,List.of("SCHEDULE","CAPACITY"),actor,"USER",null);return slotResponse(repository.findSlot(id).orElse(s));}

 @Transactional public ActivityOrderResponse createOrder(UUID user,CreateActivityOrderRequest r){MarketplaceActivityProduct p=publicProduct(r.getActivityId());ActivityPackage a=pack(r.getPackageId());ActivitySlot s=slot(r.getSlotId());if(!MarketplaceAvailabilityStatus.ENABLED.name().equals(a.getStatus())||!MarketplaceSlotStatus.ENABLED.name().equals(s.getStatus())||!a.getActivityBookingId().equals(p.getId())||!s.getPackageId().equals(a.getId()))throw notFound("Bookable activity option not found");int q=r.getQuantity();if(q<a.getMinQuantity()||a.getMaxQuantity()!=null&&q>a.getMaxQuantity())throw bad("Quantity is outside package limits");BigDecimal unit=s.getPriceOverride()==null?a.getBasePrice():s.getPriceOverride();BigDecimal total=unit.multiply(BigDecimal.valueOf(q));LocalDateTime n=LocalDateTime.now();if(repository.reserveSlot(s.getId(),q,user,n)!=1)throw conflict("Activity slot is no longer available");Map<String,Object> snap=new LinkedHashMap<>();snap.put("activity",p);snap.put("package",a);snap.put("slot",s);ActivityOrder o=ActivityOrder.builder().id(UUID.randomUUID()).orderCode(orderCode()).userId(user).organizationId(p.getOrganizationId()).activityBookingId(p.getId()).slotId(s.getId()).participantInfo(json(list(r.getParticipants()))).currency(a.getCurrency()).subtotalAmount(total).taxAmount(BigDecimal.ZERO).feeAmount(BigDecimal.ZERO).discountAmount(BigDecimal.ZERO).totalAmount(total).orderStatus(MarketplaceBookingStatus.PENDING_PAYMENT.name()).paymentStatus(MarketplacePaymentStatus.UNPAID.name()).snapshot(json(snap)).dataVersion(1L).createdBy(user).updatedBy(user).createdAt(n).updatedAt(n).build();ActivityOrderItem i=ActivityOrderItem.builder().id(UUID.randomUUID()).orderId(o.getId()).packageId(a.getId()).quantity(q).unitPrice(unit).totalPrice(total).snapshot(json(snap)).createdAt(n).build();repository.insertOrder(o);repository.insertOrderItem(i);history.record(p.getOrganizationId(),"ACTIVITY_ORDER",o.getId(),"CREATED",o,List.of(),user,"USER",null);return orderResponse(repository.findOrder(o.getId()).orElse(o));}
 public List<ActivityOrderResponse> listMyOrders(UUID u,int p,int s){Page r=page(p,s);return repository.findOrdersByUser(u,r.limit,r.offset).stream().map(this::orderResponse).toList();}
 public ActivityOrderResponse getMyOrder(UUID u,UUID id){ActivityOrder o=order(id);if(!u.equals(o.getUserId()))throw forbidden();return orderResponse(o);}
 @Transactional public ActivityOrderResponse cancelMyOrder(UUID u,UUID id,String reason,Long v){ActivityOrder o=order(id);if(!u.equals(o.getUserId()))throw forbidden();return transition(o,MarketplaceBookingStatus.CANCELLED_BY_GUEST,reason,v,u,"USER");}
 public List<ActivityOrderResponse> partnerOrders(UUID a,UUID org,String status,int p,int s){authorization.requireOrganization(org,a);Page r=page(p,s);return repository.findOrdersByOrganization(org,clean(status),r.limit,r.offset).stream().filter(o->authorization.hasResourcePermission(org,a,"ACTIVITY",o.getActivityBookingId(),"ORDER_READ")).map(this::orderResponse).toList();}
 public ActivityOrderResponse partnerOrder(UUID a,UUID id){ActivityOrder o=order(id);authorization.requireResourcePermission(o.getOrganizationId(),a,"ACTIVITY",o.getActivityBookingId(),"ORDER_READ");return orderResponse(o);}
 @Transactional public ActivityOrderResponse partnerOrderStatus(UUID a,UUID id,UpdateActivityOrderStatusRequest r){ActivityOrder o=order(id);authorization.requireResourcePermission(o.getOrganizationId(),a,"ACTIVITY",o.getActivityBookingId(),"ORDER_WRITE");requireOperatorTarget(r.getOrderStatus());return transition(o,r.getOrderStatus(),r.getReason(),r.getExpectedVersion(),a,"USER");}
 public List<MarketplaceActivityResponse> adminProducts(String q,String s,int p,int z){Page r=page(p,z);return repository.findProductsAdmin(clean(q),clean(s),r.limit,r.offset).stream().map(this::productResponse).toList();}
 public MarketplaceActivityResponse adminProduct(UUID id){return productResponse(product(id));}
 public List<ActivityPackageResponse> adminPackages(UUID id){product(id);return repository.findPackages(id,true).stream().map(this::packageResponse).toList();}
 public List<ActivitySlotResponse> adminSlots(UUID id,LocalDateTime from){pack(id);return repository.findSlots(id,from==null?LocalDateTime.now().minusYears(1):from,true).stream().map(this::slotResponse).toList();}
 public ActivityOrderResponse adminOrder(UUID id){return orderResponse(order(id));}
 @Transactional public MarketplaceActivityResponse adminProductStatus(UUID actor,UUID id,MarketplacePublicationStatus status,String reason,Long expectedVersion){MarketplaceActivityProduct p=product(id);p.setProductStatus(status.name());p.setDataVersion(requiredVersion(expectedVersion));p.setUpdatedBy(actor);p.setUpdatedAt(LocalDateTime.now());optimistic(repository.updateProduct(p),"Activity");p.setDataVersion(p.getDataVersion()+1);history.record(p.getOrganizationId(),"ACTIVITY_PRODUCT",id,"ADMIN_STATUS_CHANGED",p,List.of("productStatus"),actor,"ADMIN",reason);return productResponse(repository.findProduct(id).orElse(p));}
 public List<ActivityOrderResponse> adminOrders(String q,String s,int p,int z){Page r=page(p,z);return repository.findOrdersAdmin(clean(q),clean(s),r.limit,r.offset).stream().map(this::orderResponse).toList();}
 @Transactional public ActivityOrderResponse adminOrderStatus(UUID actor,UUID id,UpdateActivityOrderStatusRequest r){requireOperatorTarget(r.getOrderStatus());return transition(order(id),r.getOrderStatus(),r.getReason(),r.getExpectedVersion(),actor,"ADMIN");}
 @Transactional public MarketplaceActivityResponse adminCreateProduct(UUID actor,UpsertMarketplaceActivityRequest r){return partnerCreate(actor,r);}@Transactional public MarketplaceActivityResponse adminUpdateProduct(UUID actor,UUID id,UpsertMarketplaceActivityRequest r){long expected=requiredVersion(r.getExpectedVersion());MarketplaceActivityProduct current=product(id);if(MarketplacePublicationStatus.SUSPENDED.name().equals(current.getProductStatus())){adminProductStatus(actor,id,MarketplacePublicationStatus.DISABLED,"Admin editing suspended activity",expected);r.setExpectedVersion(expected+1);}return partnerUpdate(actor,id,r);}
 @Transactional public ActivityPackageResponse adminCreatePackage(UUID actor,UUID activityId,UpsertActivityPackageRequest r){return partnerCreatePackage(actor,activityId,r);}@Transactional public ActivityPackageResponse adminUpdatePackage(UUID actor,UUID id,UpsertActivityPackageRequest r){return partnerUpdatePackage(actor,id,r);}
 @Transactional public ActivitySlotResponse adminCreateSlot(UUID actor,UUID packageId,UpsertActivitySlotRequest r){return partnerCreateSlot(actor,packageId,r);}@Transactional public ActivitySlotResponse adminUpdateSlot(UUID actor,UUID id,UpsertActivitySlotRequest r){return partnerUpdateSlot(actor,id,r);}

 private ActivityOrderResponse transition(ActivityOrder o,MarketplaceBookingStatus target,String reason,Long requested,UUID actor,String type){try{if(!MarketplaceBookingStatus.valueOf(o.getOrderStatus()).canTransitionTo(target))throw bad("Invalid order transition: "+o.getOrderStatus()+" -> "+target);}catch(IllegalArgumentException ex){throw bad("Invalid stored order status: "+o.getOrderStatus());}ActivityOrderItem i=repository.findOrderItem(o.getId()).orElseThrow(()->notFound("Order item not found"));if(target.confirmsReservedInventory()){if(repository.confirmSlot(o.getSlotId(),i.getQuantity(),actor,LocalDateTime.now())!=1)throw conflict("Reserved slot inventory is inconsistent");}else if(target.releasesInventory()){boolean reserved=MarketplaceBookingStatus.PENDING_PAYMENT.name().equals(o.getOrderStatus());if(repository.releaseSlot(o.getSlotId(),i.getQuantity(),reserved,actor,LocalDateTime.now())!=1)throw conflict("Allocated slot inventory is inconsistent");}optimistic(repository.updateOrderStatus(o.getId(),requiredVersion(requested),target.name(),actor,LocalDateTime.now()),"Activity order");ActivityOrder saved=order(o.getId());history.record(saved.getOrganizationId(),"ACTIVITY_ORDER",saved.getId(),"STATUS_CHANGED",saved,List.of("orderStatus"),actor,type,reason);return orderResponse(saved);}
 private void requireOperatorTarget(MarketplaceBookingStatus target){if(!target.canBeSetByOperator())throw bad("Only the guest can set CANCELLED_BY_GUEST");}
 private void applyProductDetails(MarketplaceActivityProduct p,UpsertMarketplaceActivityRequest r){List<String> images=list(r.getImages());List<String> destinations=list(r.getDestinations());List<GeoCoordinateDto> coordinates=list(r.getDestinationCoordinates());validateCoordinates(coordinates);p.setUrl(clean(r.getUrl()));p.setRedirectUrl(clean(r.getRedirectUrl()));p.setTitle(r.getTitle().trim());p.setDescription(clean(r.getDescription()));p.setActivityAddress(clean(r.getActivityAddress()));p.setDepartingFrom(clean(r.getDepartingFrom()));p.setDestinations(json(destinations));p.setDestinationCoordinates(json(coordinates));p.setNavigationList(json(list(r.getNavigationList())));p.setItineraryStops(json(list(r.getItineraryStops())));p.setPickupAddresses(json(list(r.getPickupAddresses())));p.setSearchLat(coordinates.isEmpty()?null:coordinates.get(0).getLat().doubleValue());p.setSearchLng(coordinates.isEmpty()?null:coordinates.get(0).getLng().doubleValue());p.setDestinationsNorm(destinations.stream().filter(Objects::nonNull).map(value->value.trim().toLowerCase(Locale.ROOT)).filter(value->!value.isBlank()).collect(java.util.stream.Collectors.joining("|")));p.setPriceAmount(r.getPriceAmount());p.setPriceCurrency(r.getPriceCurrency().toUpperCase(Locale.ROOT));p.setDurationRaw(clean(r.getDurationRaw()));p.setDurationHours(r.getDurationHours());p.setVisitDurationMinutes(r.getVisitDurationMinutes());p.setThumbnail(clean(r.getThumbnail())==null?(images.isEmpty()?null:images.get(0)):clean(r.getThumbnail()));p.setImages(json(images));p.setHighlights(json(list(r.getHighlights())));p.setWhatToExpect(json(list(r.getWhatToExpect())));p.setItinerary(json(list(r.getItinerary())));}
 private void validateCoordinates(List<GeoCoordinateDto> values){for(GeoCoordinateDto value:values){if(value==null||value.getLat()==null||value.getLng()==null||value.getLat().compareTo(BigDecimal.valueOf(-90))<0||value.getLat().compareTo(BigDecimal.valueOf(90))>0||value.getLng().compareTo(BigDecimal.valueOf(-180))<0||value.getLng().compareTo(BigDecimal.valueOf(180))>0)throw bad("destinationCoordinates must contain valid latitude and longitude values");}}
 private MarketplaceActivityResponse productResponse(MarketplaceActivityProduct p){return MarketplaceActivityResponse.builder().id(p.getId()).organizationId(p.getOrganizationId()).placeId(p.getPlaceId()).placeTitle(p.getPlaceTitle()).externalId(p.getExternalId()).source(p.getSource()).url(p.getUrl()).redirectUrl(p.getRedirectUrl()).title(p.getTitle()).description(p.getDescription()).activityAddress(p.getActivityAddress()).departingFrom(p.getDepartingFrom()).destinations(readList(p.getDestinations(),String.class)).destinationCoordinates(readList(p.getDestinationCoordinates(),GeoCoordinateDto.class)).navigationList(readList(p.getNavigationList(),String.class)).itineraryStops(readList(p.getItineraryStops(),String.class)).pickupAddresses(readList(p.getPickupAddresses(),String.class)).priceAmount(p.getPriceAmount()).priceCurrency(p.getPriceCurrency()).durationRaw(p.getDurationRaw()).durationHours(p.getDurationHours()).visitDurationMinutes(p.getVisitDurationMinutes()).rating(p.getRating()).reviewCount(p.getReviewCount()).bookedCount(p.getBookedCount()).thumbnail(p.getThumbnail()).images(readList(p.getImages(),String.class)).highlights(readList(p.getHighlights(),String.class)).whatToExpect(readList(p.getWhatToExpect(),com.ds.goroute.dto.ActivityWhatToExpectItem.class)).itinerary(readList(p.getItinerary(),com.ds.goroute.dto.ActivityItineraryItem.class)).productStatus(p.getProductStatus()).inventoryMode(p.getInventoryMode()).dataVersion(p.getDataVersion()).createdAt(p.getCreatedAt()).updatedAt(p.getUpdatedAt()).build();}
 private ActivityPackageResponse packageResponse(ActivityPackage a){return ActivityPackageResponse.builder().id(a.getId()).activityId(a.getActivityBookingId()).code(a.getCode()).name(a.getName()).description(a.getDescription()).currency(a.getCurrency()).basePrice(a.getBasePrice()).minQuantity(a.getMinQuantity()).maxQuantity(a.getMaxQuantity()).attributes(readMap(a.getAttributes())).cancellationPolicy(readMap(a.getCancellationPolicy())).status(a.getStatus()).dataVersion(a.getDataVersion()).createdAt(a.getCreatedAt()).updatedAt(a.getUpdatedAt()).build();}
 private ActivitySlotResponse slotResponse(ActivitySlot s){return ActivitySlotResponse.builder().id(s.getId()).packageId(s.getPackageId()).startsAt(s.getStartsAt()).endsAt(s.getEndsAt()).timezone(s.getTimezone()).capacity(s.getCapacity()).reservedQuantity(s.getReservedQuantity()).soldQuantity(s.getSoldQuantity()).blockedQuantity(s.getBlockedQuantity()).availableQuantity(s.getAvailableQuantity()).bookingCutoffMinutes(s.getBookingCutoffMinutes()).priceOverride(s.getPriceOverride()).status(s.getStatus()).dataVersion(s.getDataVersion()).createdAt(s.getCreatedAt()).updatedAt(s.getUpdatedAt()).build();}
 private ActivityOrderResponse orderResponse(ActivityOrder o){ActivityOrderItem i=repository.findOrderItem(o.getId()).orElse(null);ActivityOrderItemResponse ir=i==null?null:ActivityOrderItemResponse.builder().id(i.getId()).packageId(i.getPackageId()).packageName(i.getPackageName()).quantity(i.getQuantity()).unitPrice(i.getUnitPrice()).totalPrice(i.getTotalPrice()).snapshot(readMap(i.getSnapshot())).build();return ActivityOrderResponse.builder().id(o.getId()).orderCode(o.getOrderCode()).userId(o.getUserId()).organizationId(o.getOrganizationId()).activityId(o.getActivityBookingId()).activityTitle(o.getActivityTitle()).slotId(o.getSlotId()).participants(readValue(o.getParticipantInfo(),new TypeReference<List<Map<String,Object>>>(){},List.of())).currency(o.getCurrency()).subtotalAmount(o.getSubtotalAmount()).taxAmount(o.getTaxAmount()).feeAmount(o.getFeeAmount()).discountAmount(o.getDiscountAmount()).totalAmount(o.getTotalAmount()).orderStatus(o.getOrderStatus()).paymentStatus(o.getPaymentStatus()).voucherCode(o.getVoucherCode()).dataVersion(o.getDataVersion()).item(ir).createdAt(o.getCreatedAt()).updatedAt(o.getUpdatedAt()).build();}
 private MarketplaceActivityProduct product(UUID id){return repository.findProduct(id).orElseThrow(()->notFound("Activity not found"));}private MarketplaceActivityProduct publicProduct(UUID id){return repository.findPublicProduct(id).orElseThrow(()->notFound("Activity not found"));}private ActivityPackage pack(UUID id){return repository.findPackage(id).orElseThrow(()->notFound("Package not found"));}private ActivitySlot slot(UUID id){return repository.findSlot(id).orElseThrow(()->notFound("Slot not found"));}private ActivityOrder order(UUID id){return repository.findOrder(id).orElseThrow(()->notFound("Activity order not found"));}
 private boolean organizationBookable(UUID organizationId){return organizationId!=null&&organizationRepository.findById(organizationId).map(o->OrganizationOperationalStatus.ENABLED.name().equals(o.getOperationalStatus())&&!OrganizationVerificationStatus.SUSPENDED.name().equals(o.getVerificationStatus())).orElse(false);}
 private void validatePackage(UpsertActivityPackageRequest r){currency(r.getCurrency());if(r.getMaxQuantity()!=null&&r.getMaxQuantity()<r.getMinQuantity())throw bad("maxQuantity must be >= minQuantity");}private void validateSlot(UpsertActivitySlotRequest r){try{ZoneId.of(r.getTimezone());}catch(Exception e){throw bad("Invalid IANA timezone");}if(r.getEndsAt()!=null&&!r.getEndsAt().isAfter(r.getStartsAt()))throw bad("endsAt must be after startsAt");if(r.getBlockedQuantity()>r.getCapacity())throw bad("blockedQuantity exceeds capacity");}private void currency(String v){try{Currency.getInstance(v);}catch(Exception e){throw bad("Invalid currency");}}
 private long requiredVersion(Long value){if(value==null||value<1)throw bad("expectedVersion is required for an update");return value;}private void optimistic(int n,String x){if(n!=1)throw conflict(x+" was changed or violates allocated inventory");}private String orderCode(){return "ACT-"+LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE)+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();}private String code(String s){return s.trim().toUpperCase(Locale.ROOT);}private String clean(String s){return s==null||s.isBlank()?null:s.trim();}private String enumNameOrDefault(Enum<?> value,Enum<?> fallback){return value==null?fallback.name():value.name();}private String enumNameOrDefault(Enum<?> value,String fallback){return value==null?fallback:value.name();}private String partnerPublicationStatus(MarketplacePublicationStatus value,String fallback){String status=enumNameOrDefault(value,fallback);if(MarketplacePublicationStatus.SUSPENDED.name().equals(status))throw new BusinessException(ErrorConstant.FORBIDDEN_ERROR,"Only an admin can suspend an activity");return status;}private <T>List<T> list(List<T> v){return v==null?List.of():v;}private <K,V>Map<K,V> map(Map<K,V> v){return v==null?Map.of():v;}
 private String actorType(UUID actor){return actor!=null&&adminMapper.hasAnyRole(actor)?"ADMIN":"USER";}
 private String json(Object v){try{return objectMapper.writeValueAsString(v);}catch(JsonProcessingException e){throw new BusinessException(ErrorConstant.INTERNAL_SERVER_ERROR,"Cannot serialize activity data");}}private Map<String,Object> readMap(String v){return readValue(v,new TypeReference<Map<String,Object>>(){},Map.of());}private <T>List<T> readList(String v,Class<T> c){if(v==null)return List.of();try{return objectMapper.readValue(v,objectMapper.getTypeFactory().constructCollectionType(List.class,c));}catch(Exception e){return List.of();}}private <T>T readValue(String v,TypeReference<T> t,T f){if(v==null)return f;try{return objectMapper.readValue(v,t);}catch(Exception e){return f;}}
 private Page page(int p,int s){int l=Math.min(Math.max(s,1),200);return new Page(l,Math.max(p,0)*l);}private BusinessException bad(String m){return new BusinessException(ErrorConstant.BAD_REQUEST,m);}private BusinessException conflict(String m){return new BusinessException(ErrorConstant.ALREADY_PROCESSED,m);}private BusinessException notFound(String m){return new BusinessException(ErrorConstant.NOT_FOUND,m);}private BusinessException forbidden(){return new BusinessException(ErrorConstant.FORBIDDEN_ERROR,"You cannot access this activity order");}private record Page(int limit,int offset){}
}
