package com.ds.goroute.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class MarketplaceActivityProduct {
    private UUID id;
    private UUID organizationId;
    private UUID placeId;
    private String placeTitle;
    private String externalId;
    private String source;
    private String activityType;
    private String url;
    private String redirectUrl;
    private String title;
    private String description;
    private String activityAddress;
    private String departingFrom;
    private String destinations;
    private String destinationCoordinates;
    private Double searchLat;
    private Double searchLng;
    private String destinationsNorm;
    private String navigationList;
    private String itineraryStops;
    private String pickupAddresses;
    private String languages;
    private String meetingPoint;
    private String includedItems;
    private String excludedItems;
    private String eligibility;
    private String accessibilityFeatures;
    private String confirmationType;
    private String voucherType;
    private String redemptionInstructions;
    private String cancellationPolicy;
    private String requiredInformation;
    private BigDecimal priceAmount;
    private String priceCurrency;
    private String durationRaw;
    private BigDecimal durationHours;
    private Integer visitDurationMinutes;
    private BigDecimal rating;
    private Integer reviewCount;
    private Integer bookedCount;
    private String thumbnail;
    private String images;
    private String highlights;
    private String whatToExpect;
    private String itinerary;
    private String goodToKnow;
    private String faqs;
    private String videoUrl;
    private String operatorName;
    private String productStatus;
    private String inventoryMode;
    private Long dataVersion;
    private UUID createdBy;
    private UUID updatedBy;
    private UUID locationImageId;private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
